"""Define somme constants"""

ROUND_QUANTITY = 4
ROUND_QUANTITY_MIN = 3
ROUND_QUANTITY_MAX = 6

PLAYER_NAME_LENGTH = 20
PLAYER_SURNAME_LENGTH = 20
PLAYER_QUANTITY_MIN = 8

TOURNAMENT_NAME_LENGTH = 20
TOURNAMENT_PLACE_LENGTH = 30
TOURNAMENT_DESCRIPTION_LENGTH = 50

ORDER_ALPHA = 1
ORDER_CLASSIFICATION = 2
